BZ-18845: fix: select component
juspay/svelte-ui-components pull request #34
Opened 2024-04-23 03:57 UTC by anjalideswal

- added showDropDownArrow optional property to toggle arrow visbility
- added dynamic css variables for box-shadow, hover background-color, selected-option-icon

2024-04-23 04:36 UTC, vishalbhardwaj7 approved these changes

2024-04-23 07:26 UTC, rab1prasad approved these changes

2024-04-23 16:56 UTC, murdore requested changes

2024-04-23 16:56 UTC, murdore commented on src/lib/Select/Select.svelte
> +          src="https://sdk.breeze.in/gallery/icons/right-arrow.svg"
can we pass this as input? also expose the alt tag to be passed by component user

2024-04-25 08:47 UTC, sinha-sahil commented
@anjalideswal This seems to be more of a enhancement than a fix. Kindly, update the type.

2024-04-30 10:09 UTC, anjalideswal commented on src/lib/Select/Select.svelte
> +          src="https://sdk.breeze.in/gallery/icons/right-arrow.svg"
Done. Added `dropDownIcon` as optional prop. If not passed, drop down icon will not be added, to handle drop down icon visibility. Added altText export

2024-04-30 11:54 UTC, murdore approved these changes

2024-04-30 11:57 UTC, rab1prasad commented on src/lib/Select/Select.svelte
> +  export let altText = '';
rename, please specify for whom this alt tex is for.

2024-04-30 11:57 UTC, rab1prasad commented on src/lib/Select/properties.ts
> +  dropDownIcon?: string | null;
Do we need this `?` if using null?

I think we should have 2 different props one for `showDropDownIcon` one for dropdown icon, and a default icon should be provided if icon is not passed as prop.

2024-05-02 06:38 UTC, rab1prasad approved these changes

2024-05-06 06:25 UTC, kingk5 approved these changes

2024-05-07 07:24 UTC, murdore commented
@anjalideswal resolve conflicts and add proof of testing

2024-05-07 07:49 UTC, murdore approved these changes

2024-05-07 07:49 UTC, murdore commented on src/lib/Select/Select.svelte
> +        <img
@anjalideswal lets use the Image component from svelteComponents.
Check @adarshjuspay 's pr for reference

2024-05-07 08:11 UTC, merged